### PR TITLE
add Close() method to server

### PR DESCRIPTION
**Pull request by ngaut**
New simple implementation, please review it

### CODE REVIEW

**Comment by dim** [comment]
Thanks, will review. Quick question about the intention here: why would you want to close all client connections explicitly. If you stopped the server from listening, you would also terminate all client connections. Could you please clarify?

**Comment by ngaut** [comment]
Well, since we need a way to simulate close redis, The close action of redeo is diffrent from real redis.
We are using miniredis for testing,  and miniredis depends on cool redeo. thanks

**Comment by ngaut** [comment]
@dim Any suggestions?

**Comment by dim** [comment]
Is this what you are looking for? e073d245ba51b684aa77cf8db93227235cee40e0

**Comment by ngaut** [comment]
yes, thank you :)

**Pull request closed without merging**
